; DO NOT EDIT THIS FILE
; This file is generated by the assembler
.IRQ              = 0x8005
.MMC1_reset       = 0xBFE8
.MMC1_set_chr_bank_0 = 0xBFAC
.MMC1_set_chr_bank_1 = 0xBFC0
.MMC1_set_control = 0xBF98
.MMC1_set_prg_bank = 0xBFD4
.NMI              = 0x8004
.RESET            = 0xBF50
.RESET_wait1      = 0xBF72
.RESET_wait2      = 0xBF7C
.START            = 0x8001

