; Lifted from The Legend of Zelda
    SEI                         ; Disable interrupts
    CLD                         ; Clear decimal flag
    LDA     #0x00               ; Clear the PPU control register ...
    STA     PPU_control_1       ; ... truns off NMI source
    LDX     #0xFF               ; Set stack pointer ...
    TXS                         ; ... to 01FF

_wait1:
    LDA     PPU_status          ; Wait ...
    AND     #0x80               ; ... for ...
    BEQ     _wait1              ; ... VBLANK
_wait2:
    LDA     PPU_status          ; Wait ...
    AND     #0x80               ; ... for another ...
    BEQ     _wait2              ; ... VBLANK

    ORA     #0xFF               ; Reset ...
    STA     MMC_Control         ; ... ...
    STA     MMC_CHR_Bank0       ; ... all ...
    STA     MMC_CHR_Bank1       ; ... four ...
    STA     MMC_PRG_Bank        ; ... MMC1 registers
;
; After resetting the MMC1, we are running in bank 7
;
    LDA     #0x0F               ; Set MMC control to 8K CHR ROM, fixed/bank 16K PRG pages, ...
    JSR     MMC_set_control     ; ... and horizontal mirroring (vertical scrolling)
    LDA     #0x00               ; Set VROM bank ...
    JSR     MMC_set_chr_bank_0  ; ... to bank 0    
    LDA     #0x07               ; Repeat bank 7 ...
    JSR     MMC_set_prg_bank    ; ... in the low ROM bank
;
    JMP     START               ; Start of game