; Copy a block of memory from CPU ram to PPU ram

PPU_copy_block_to_vram:
; GP0 = (word) source address
; GP1 = (word) VRAM destination address
; GP2 = (word) number of bytes to copy
;
    lda     PPUSTATUS            ; Clear address vram address latch
;
    lda     GP1+1                ; VRAM ...
    sta     PPUADDR              ; ... MSB
    lda     GP1                  ; VRAM ...
    sta     PPUADDR              ; ... LSB
;
    ldy     #0x00                ; 0 offset in next read
_copyLoop:
    lda     (GP0),Y              ; Read byte from ROM
    sta     PPUDATA              ; Write byte to VRAM
;
    lda     GP0                  ; Increment ...
    clc                          ; ... two ...
    adc     #0x01                ; ... byte ...
    sta     GP0                  ; ... pointer ...
    lda     GP0+1                ; ... at ...
    adc     #0x00                ; ... 00 and ...
    sta     GP0+1                ; ... 01
;
    lda     GP2                  ; Decrement ...
    sec                          ; ... two ...
    sbc     #0x01                ; ... byte ...
    sta     GP2                  ; ... count ...
    lda     GP2+1                ; ... at ...
    sbc     #0x00                ; ... 02 and ...
    sta     GP2+1                ; ... 03
;
    lda     GP2                  ; More to do?
    bne     _copyLoop            ; Yes ... go move all
    lda     GP2+1                ; More to do?
    bne     _copyLoop            ; Yes ... go move all
    rts